"""
Django settings for hemosc_app project.

Generated by 'django-admin startproject' using Django 4.1.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

import mongoengine

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-hfor0=1vh*q$=(_380k!v-e2g=jdt$k&)0o=fkvqddw7-^w*!f"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*", "localhost", "hemosc_app-main-344w6pdugq-uc.a.run.app"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core",
    # "django_mongoengine",
    # "django_mongoengine.mongo_auth",
    # "django_mongoengine.mongo_admin",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    # "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# AUTH_USER_MODEL = "mongo_auth.MongoUser"

# AUTHENTICATION_BACKENDS = ("django_mongoengine.mongo_auth.backends.MongoEngineBackend",)

# SESSION_ENGINE = "django_mongoengine.sessions"

ROOT_URLCONF = "hemosc_app.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "hemosc_app.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# MONGODB_DATABASES = {
#     "default": {
#         "name": "hemosc_app",
#         "host": "mongodb+srv://hemosc_app:EqPVNgnOl5XdeSU5@hemosc_app.ugjj0xo.mongodb.net/?retryWrites=true&w=majority&appName=hemosc_app",
#         "password": "EqPVNgnOl5XdeSU5",
#         "username": "hemosc_app",
#         "tz_aware": True,  # if you using timezones in django (USE_TZ = True)
#         "engine": "django_mongoengine.mongoengine.django.db",
#     },
#     "engine": "django_mongoengine.mongoengine.django.db",
# }
# DATABASES = {
#     "default": {
#         "ENGINE": "djongo",
#         "NAME": "hemosc_app",
#     }
# }

DB_NAME = "hemosc_app"
DB_USER = "hemosc_app"
DB_PASS = "hemosc_app"
HOST = "mongodb+srv://127.0.0.1:27017/?retryWrites=true&w=majority&appName=hemosc_app"

mongoengine.connect(
    db=DB_NAME,
    host=HOST,
    username=DB_USER,
    password=DB_PASS,
    serverSelectionTimeoutMS=1000,
)


DATABASES = {
    "default": {
        "ENGINE": "djongo",
        "NAME": DB_NAME,
        "ENFORCE_SCHEMA": False,
        "CLIENT": {"host": HOST},
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
